server:
	g++ -std=c++17 -Wall -Wextra -o bin/Server src/ServerMain.cpp src/Server.cpp && bin/Server

client:
	clang++ -std=c++17 -Wall -Wextra -o bin/Client src/ClientMain.cpp src/Client.cpp && bin/Client