server:
	g++ -std=c++17 -Wall -Wextra -o bin/Server src/ServerMain.cpp src/Server.cpp src/TcpConnection.cpp && bin/Server

client:
	g++ -std=c++17 -Wall -Wextra -o bin/Client src/ClientMain.cpp src/Client.cpp && bin/Client